# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nr_ST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_product', models.CharField(max_length=15)),
                ('name_product', models.CharField(max_length=100)),
                ('date_of_acceptance', models.DateField()),
                ('value_product', models.PositiveIntegerField()),
                ('user', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='')),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Nr_STC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_product', models.CharField(max_length=15)),
                ('name_product', models.CharField(max_length=100)),
                ('date_of_acceptance', models.DateField()),
                ('value_product', models.PositiveIntegerField()),
                ('user', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='')),
                ('note', models.TextField()),
                ('nr_st', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Nr_ST')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='nr_st',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Owner'),
        ),
    ]
