# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_owner_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='nick_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
