# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20170128_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nr_st',
            name='value_product',
            field=models.PositiveIntegerField(verbose_name='null'),
        ),
    ]
