# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20170128_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nr_st',
            name='nr_product',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
